package com.jamming_dino.jd_resource_nodes.datagen;

import com.jamming_dino.jd_resource_nodes.ResourceNodeTier;
import com.jamming_dino.jd_resource_nodes.ResourceNodes;
import com.jamming_dino.jd_resource_nodes.block.ResourceNodeBlock;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.client.model.generators.BlockStateProvider;
import net.neoforged.neoforge.client.model.generators.ConfiguredModel;
import net.neoforged.neoforge.client.model.generators.ModelFile;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.registries.DeferredBlock;

public class ResourceNodesModelProvider extends BlockStateProvider {
    public ResourceNodesModelProvider(PackOutput output, ExistingFileHelper exFileHelper) {
        super(output, ResourceNodes.MODID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
        for (DeferredBlock<ResourceNodeBlock> holder : ResourceNodes.REGISTERED_NODES) {
            ResourceNodeBlock block = holder.get();
            String path = holder.getId().getPath(); // e.g. "node_iron_pure"

            ResourceNodeTier tier = getTierFromPath(path);
            String tierName = tier.getSerializedName();

            // 1. Determine Texture Names
            // We use the files generated by TextureBaker
            // Ore Texture: "node_iron_pure" (matches block name usually)
            // Stone Texture: "node_stone_pure" (derived from base block)

            // Special Case: Ancient Debris (Column)
            boolean isDebris = block.getOriginalOre() == Blocks.ANCIENT_DEBRIS;

            ModelFile oreModel;
            ModelFile stoneModel;

            // Derive Base Name for the "Regenerating" texture
            // e.g. "stone" -> "node_stone_pure"
            // e.g. "deepslate" -> "node_deepslate_pure"
            String baseBlockName = BuiltInRegistries.BLOCK.getKey(block.getBaseBlock()).getPath();
            ResourceLocation stoneTexture = modLoc("block/node_" + baseBlockName + "_" + tierName);

            if (isDebris) {
                // Ancient Debris - Column Model
                ResourceLocation sideTex = modLoc("block/node_ancient_debris_" + tierName + "_side");
                ResourceLocation topTex = modLoc("block/node_ancient_debris_" + tierName + "_top");

                oreModel = models().cubeColumn(path + "_ore", sideTex, topTex);

                // Regenerating (Netherrack) is just a cube
                stoneModel = models().cubeAll(path + "_stone", stoneTexture);

            } else {
                // Standard Ore - Cube Model
                ResourceLocation oreTexture = modLoc("block/" + path);

                oreModel = models().cubeAll(path + "_ore", oreTexture);
                stoneModel = models().cubeAll(path + "_stone", stoneTexture);
            }

            // 2. Register BlockState
            getVariantBuilder(block).forAllStates(state -> {
                boolean regenerating = state.getValue(ResourceNodeBlock.REGENERATING);
                return ConfiguredModel.builder()
                        .modelFile(regenerating ? stoneModel : oreModel)
                        .build();
            });

            // 3. Item Model
            simpleBlockItem(block, oreModel);
        }
    }

    private ResourceNodeTier getTierFromPath(String path) {
        if (path.endsWith("impure")) return ResourceNodeTier.IMPURE;
        if (path.endsWith("pure")) return ResourceNodeTier.PURE;
        return ResourceNodeTier.NORMAL;
    }
}